name: challenges
description: A dart version of code challenges

publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies: 
  stack: ^0.2.1
  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'